// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx9arh86QgDvfniq2wEAVztYfoTAmN6IY',
    appId: '1:350307662606:android:fed4bdfd341b1d9f37355f',
    messagingSenderId: '350307662606',
    projectId: 'supermarketshoppinglist-93eaf',
    storageBucket: 'supermarketshoppinglist-93eaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQd_FXRx9cL9uZEBsgO8TYU4lg0WDhXqE',
    appId: '1:350307662606:ios:ae6bb54b41a396b837355f',
    messagingSenderId: '350307662606',
    projectId: 'supermarketshoppinglist-93eaf',
    storageBucket: 'supermarketshoppinglist-93eaf.firebasestorage.app',
    iosBundleId: 'com.example.minhalistadecompras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQd_FXRx9cL9uZEBsgO8TYU4lg0WDhXqE',
    appId: '1:350307662606:ios:ae6bb54b41a396b837355f',
    messagingSenderId: '350307662606',
    projectId: 'supermarketshoppinglist-93eaf',
    storageBucket: 'supermarketshoppinglist-93eaf.firebasestorage.app',
    iosBundleId: 'com.example.minhalistadecompras',
  );
}
